apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.4
          args:
            - start-dev
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: keycloak-postgres
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloak

            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
